### PR TITLE
Compatibility with AFNetworking 3.x.x

### PR DESCRIPTION
**Pull request by Ch1llb4y**
All tests ran successfully.

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
Thanks @Ch1llb4y! This looks great.
@JRG-Developer I don't have `pod trunk` access to this pod. Can you either give me access or push a new version of this today please!

**Comment by AnthonyMDev** [comment]
@Ch1llb4y Why did you remove the `UIKit` subspec from the dependency in the `podspec`? Is there a need for the `AFNetworking` core now?

**Comment by Ch1llb4y** [comment]
@AnthonyMDev Well you need AFNetworking because you call method from this framework :D

**Comment by AnthonyMDev** [comment]
@Ch1llb4y I understand that. I'm specifically asking why you removed the `UIKit` subspec specification from the dependency.

**Comment by Ch1llb4y** [comment]
What is the point on having UIKit there? Every iOS App has UIKit as a default dependency.

**Comment by AnthonyMDev** [comment]
This isn't the dependency on `UIKit` this is a dependency on `AFNetworking`'s `UIKit` subspec. 

https://guides.cocoapods.org/syntax/podspec.html#subspec for more info.

**Comment by Ch1llb4y** [comment]
Ahhh, thanks. Should I change something?

**Pull request merged**
